### ISSUE TITLE
Can I use cwipc_util to calibrate multiple RGBD cameras by using their point cloud output?

### ISSUE THREAD

**Issue by ttsesm** [cwi-dis/cwipc_util#8]
Hi @jackjansen,

I've came upon this lib and I would like to ask if it is possible to use it for calibrating multiple rgbd camera based on their point clouds.

For example I have 2 ZED2 cameras and 3 realsense (1 L515, and 2 D435) and I would like to get their extrinsic matrices, i.e. their position in the world space by calibrating them based on their point cloud output.

Would be able to do that with cwipc_util?

Thanks.

**Comment by jackjansen** [comment]
Hello @ttsesm ,
sorry for not replying sooner: we tend to use the toplevel repository <https://github.com/cwi-dis/cwipc> for issues. I will put a note here about that.

About the ZED2 and L515 I'm afraid I have bad news for you: we don't support these cameras at the moment, and we don't plan to support them. The L515 has been discontinued, and the ZED2 we feel to be an "also ran" product nowadays. We currently support the D4xx and Kinect Azure, and we are investigating support for the Orbbec cameras.

But: The L515 may work, because it uses the same underlying API as the D4xx, and we've found that newer models of the RealSense cameras would just work out of the box.

And if you're willing and able to implement the `cwipc_capturer` implementation for the ZED2 (analogous to `cwipc_kinect` and `cwipc_realsense`) we would definitely be interested. To the point that we could probably even acquire a device to ensure it keeps working. We just don't have the developer resources to do the initial implementation.

Second problem is that from your original post I get the impression that you want to use these 5 devices at the same time, to create one point cloud. At the moment this is not supported: `cwipc` can only create merged point clouds from cameras of a single brand. Only RealSense or only Kinect. We plan to allow mix-and-match, but we have no timeline for this. Again due to lack of developer resources.

But if you are interested in obtaining the extrinsic matrices for cameras of a single type (and possibly it would also work for the D435s and the L515 together): that is definitely supported. The `cwipc_register` utility does exactly this: it creates a `cameraconfig.json` file that is subsequently used by the rest of the `cwipc` software suite to capture single unified point clouds. But if you want to use different software that is also possible: the per-camera extrinsic matrices are in the JSON file.

A minor problem right now is that `cwipc_register` is very badly documented, but we are working on that at the moment (issue https://github.com/cwi-dis/cwipc/issues/103). We expect that to be done in the next few days and then we will do a new release of cwipc.
